### ISSUE TITLE
NPCs not Included

### ISSUE THREAD

**Issue by natyusha** [Infiziert90/MOActionPlugin#16]
Thanks, for the great plugin. Was wondering if you would consider allowing NPCs to be healed by mousing over them (similar to how `<mo>` works when used in a macro). They don't seem to count as field entities from what I've seen.

Edit: Targeting a healable NPC and hovering over the UI element also doesn't work.

**Comment by BDtetra** [comment]
Same goes for Players not in your party from what I tried.

**Comment by KristianUSN** [comment]
From what I gather healing NPCs doesn't work at all when using this plugin, even when targeted. Maybe I'm missing a workaround but I have to disable the plugin whenever I'm in a story duty as a healer.

**Comment by natyusha** [comment]
I'm still able to heal by manually targeting just fine.

**Comment by Hayato2846** [comment]
Hi!

I can confirm this is still a thing. Some of my action stacks combine heals and damage spells (e.g. something like this: UI MO Cure > Reg. Target Cure > Reg. Target Stone) and they continually fail in special NPC cases. Healing some friendly and healable NPCs or damaging some spawned adds just fail so I'm healing myself.

Are there any hints to avoid this?

Thanks! :)

**Comment by zehkaiser** [comment]
I've found that by dropping the last line item of "Self" it will fall through and fail everything before defaulting to the default game behavior. If you have the option enabled in your game settings it will cast spells on yourself if you don't have a target. If you do have a target and it happens to be an NPC you will heal the NPC.

**Comment by Alluneve** [comment]
Healable npcs was implemented, can be closed
