### ISSUE TITLE
Bottom buttons not visible at higher UI scale

### ISSUE THREAD

**Issue by mkaito** [Infiziert90/MOActionPlugin#24]
Doesn't matter how much I resize the window, the buttons at the bottom are never visible.

Scale 1.0:
![image](https://user-images.githubusercontent.com/20434/133130295-a04388d7-ba77-49fe-a354-da8c3ef18f77.png)

Scale 2.0: 
![image](https://user-images.githubusercontent.com/20434/133130311-95039e1c-f3d2-4414-9cc6-f8902824164f.png)

**Comment by attickdoor** [comment]
Freakin UI scaling. Every time, man. I'll see what I can do.
