### ISSUE TITLE
Nice to have - Certain abilities triggered when status met

### ISSUE THREAD

**Issue by chrismwhite** [Infiziert90/MOActionPlugin#26]
A nice feature to have would be for certain abilities are resolved one way if a condition is met, or another if its not met

Example: Dragon sight and party count is 4, and different if party count is 8, although party sorting of list could manage this somewhat.

Another example: Heart of stone, if i have active aggro, use on me, otherwise use on target of target

**Comment by Infiziert90** [comment]
The plugin shouldn't do any thinking for you, so this won't be done, sorry
