### ISSUE TITLE
BLU Aetherial Mimicry - No Mouseovers

### ISSUE THREAD

**Issue by Diorik** [Infiziert90/MOActionPlugin#28]
Aetherial Mimicry never fires on a field or UI mouse over.

**Comment by majesstic** [comment]
I've tested other Target options as well, not just UI mouseover/field mouseover. No Target option other than "target" will successfully cast Aetherial Mimicry (aka: default behavior of the spell).

Ingame, every other Target option gives an "Invalid Target" error.

Checked dalamud.log, and nothing is being logged for this - it seems like moaction configuration for this spell is simply being ignored?

**Comment by Alluneve** [comment]
This was similar to Healable battlenpcs, was fixed a long while ago, issue can be closed
