### ISSUE TITLE
Target option: nearest enemy

### ISSUE THREAD

**Issue by kaedys** [Infiziert90/MOActionPlugin#29]
I'm not sure if this is feasible, and even if it is, if it fits within the scope of what you want this mod to do, but there are a couple abilities I'd love to have automatically execute on the nearest target if I don't have one selected.

The primary use case for this, to be honest, is cone and line attacks.  I'm not sure _why_ FFXIV requires that these type attacks have a valid target, but it's annoyingly common for me to be AoEing with a cone attack (Quick Nock, Moulinet, Fuga, etc), and for my target to die and thus my AoE to stop going off unless I'm really on top of slapping the tab button the instant my target drops (and I can't simply spam tab, because FFXIV will happily tab to that target that's not in combat and that's 50 yards away in the next room, rather than just the ones in-combat and immediately in front of you).  Basically, would serve as a way of negating one of the aspects of FFXIV targeting that I find most infuriating, that an AoE attack that's _not_ target-centered still, for no rational reason I can discern, mandates you have a target that's within the area of the attack (meanwhile ground-target and PBAoEs _don't_).  It's really the only thing that keeps me from enjoying Samurai and Warrior, both of which require a cone leading to their AoE (and in the case of Samurai, also on their AoE Iuijutsu >.>).  Another use-case would be for targeted follow-up AoEs from untargeted AoEs (ex. Fan Dance II -> Fan Dance III).

Basic concept of function would be setting it after `target` in the stack list, and have it mechanically function either identically to tab target (not sure if you can just directly call the tab target functionality), or unconditionally target nearest.  Maybe both as options (target next and target nearest)?  Might also be worth having it for nearest ally, though the only real use-case I can think of for that atm would be Dragoon's Dragon Sight so you don't have to go hunting for a target or muck with focus macros for it.

If that's beyond the scope of what you want this plugin to do, though, c’est la vie.  I understand it could be seen as at least nudging the line on automation, but I feel like it's more addressing a specific weakness of the FFXIV targeting system, which is more or less what mouseover targeting is for as well.

**Comment by Infiziert90** [comment]
The plugin shouldn't do any "thinking" on your behalf, so this won't be added, sorry
