### ISSUE TITLE
Old tick abilities config menu gone?

### ISSUE THREAD

**Issue by yuealice** [Infiziert90/MOActionPlugin#30]
Is the old menu where you can just tick abilities removed in this update?

**Comment by costomojin** [comment]
sweet jesus please fix this back

**Comment by Eyliria** [comment]
I am unsure if the rewrite for the new API 4 of Dalamud precludes this functionality, or if it needs to be reworked/retooled still and to come on a future patch, but, I too would like to echo the sentiment that the ease of use this setting was king for me. Also, the stacks don't seem to be entirely working for me right now. But I should probably open a new ticket for that.

**Comment by attickdoor** [comment]
It's not coming back.
