### ISSUE TITLE
Stacks do not seem to be working - WHM, DIA

### ISSUE THREAD

**Issue by Eyliria** [Infiziert90/MOActionPlugin#32]
I have the current stack example setup ![I have the current example stack setup](https://i.imgur.com/ULaEEni.png)

And it just simply refuses to work, be it hovering over the enemy list, or just hovering over the targets on my screen.
This update seems to have broken the addon.

**Comment by Eyliria** [comment]
Follow-up.

It works so long as I use the "base level" abilities, i.e. Aero in my case example.

**Comment by bennyty** [comment]
+1, also encountered this. In my case I was experimenting, trying to cast Cure2 by pressing Stone3. The currently working way to set this up is as follows.

![working config](https://i.imgur.com/yQjiMLG.png)

And then crucially, go to your spellbook and pull out "Stone" and put it on your bar. It will upgrade to Stone3 but seems to then work.

**Comment by Infiziert90** [comment]
Closing this, if the issue still exists in newer version please reopen the issue
