### ISSUE TITLE
Japanese client

### ISSUE THREAD

**Issue by BallanTine7** [Infiziert90/MOActionPlugin#35]
I could use it with a Japanese client before the update, but after the update it can no longer be used at all.
Do you have any plans to support Japanese clients?
![image](https://user-images.githubusercontent.com/92189201/136634838-9287b7a7-bd85-447b-9ae0-036ca592a535.png)

**Comment by Infiziert90** [comment]
Closing this, if the issue still exists in newer version please reopen the issue
