### ISSUE TITLE
Missing 'Alt' Modifier Option

### ISSUE THREAD

**Issue by ManagerWoW** [Infiziert90/MOActionPlugin#36]
The new "Held Modifier Key" dropdown appears to be bugged and missing the Alt modifier from the list. 

Version: 4.0.3
https://i.imgur.com/gN7ehYx.png

**Comment by icesharkk** [comment]
same issue observed. unsure if this is a bug or just a missing feature. either way ALT is a critical modifier option and I hope the developer has a chance to update this..

**Comment by BoredDan** [comment]
Menu is ALT. The keycode is called menu internally and MoAction just uses the internal name rather then writing proper code to convert it.
