### ISSUE TITLE
Mouse Location stack does not check for cooldown / gcd / resources

### ISSUE THREAD

**Issue by Electrized** [Infiziert90/MOActionPlugin#38]
As of current, unlike the similar feature from akira0245's smartcast (currently unavailable on api4), MOAction stacks with the property "Mouse Location" on an ability such as Feather Rain, Sacred Soil, or any other 3d world targeted ability does NOT account for cooldown / gcd or even missing resources and will play the animation of the ability regardless

I have 0 idea on how to fix this, but it might be of use looking at how akira0245's smartcast handles checks for being able to cast the spell

Also, this is NOT an issue on any of the other stack properties such as field / ui mouseovers from my experience, only Mouse Location 

Heres a clip to demonstrate what happens when casting sacred soil with 0 resources / during GCD: https://streamable.com/38dn73

**Comment by Electrized** [comment]
Seemingly skips the clientside check for "is this ability ready" and sends the "place action" packet directly to the server, where the server denies it

**Comment by wozaiha** [comment]
Mo didn't even check whether the place should be able to place a ground target skill and just send it… I am not sure whether this may lead to a ban. 
The source code is never updated so even a fix PR is impossible even I have worked with Akira and fixed some part of it.

**Comment by bladehawkz** [comment]
There also appears to be a problem with 'special' platforms, such as e4s. Asylum just attempts to, (and if range will cast) fly to the edge of the map instead of where it's targetted.

Now that Akira's is updated to API4 it's not too much of a problem using his implementation instead, but notably his doesn't put the ability in queue though.

**Comment by Infiziert90** [comment]
Closing this, if the issue still exists please reopen
