### ISSUE TITLE
Target > Focus Target is an invalid priority when Focus Target is untargetable

### ISSUE THREAD

**Issue by Kanarisky** [Infiziert90/MOActionPlugin#42]
If you setup a stack for an offensive spell like this, and your focus target goes untargetable, you will not be able to cast the spell on your target, unless you un-focus your focus target:
![image](https://user-images.githubusercontent.com/68185248/137583140-ea72a7dc-7116-4f49-9d46-b2b46b5edc35.png)

For example, enter The Navel and focus target Titan. Now target Titan. You can successfully cast malefic IV on him using the stack above.
Now progress to his "heart" phase, where Titan (your focus target) becomes untargetable. Target "Titan's Heart" and try to cast Malefic IV. You can't (invalid target), unless you remove Titan as your focus target. This is despite the fact that "Target" is higher in the stack than "Focus Target" is...

![image](https://user-images.githubusercontent.com/68185248/137583226-e8ce8f77-ee45-4cb5-a67f-6145123d1c0a.png)

Finally, I'll add that Target > Focus Target works perfectly fine when the focus target isn't untargetable. For example if you focus target Dummy 1 and target Dummy 2, your spell will fire on Dummy 2. If you untarget Dummy 2, your spell will fire on Dummy 1.

**Comment by Alluneve** [comment]
Titans heart as a specific target was an issue before the re-write to canuseTarget as it is a unique target type (not a battlenpc)

Issue can be closed
