### ISSUE TITLE
Nocturnal Sect - Aspected Benefic failed to follow stacks if i press it too fast

### ISSUE THREAD

**Issue by FakeGodz** [Infiziert90/MOActionPlugin#43]
While i am on Nocturnal Sect as Astrology, whenever i press Aspected Benefic way too fast, it'll just cast it on myself (or my target) and ignore my stack setting.

My stack is just simple UI Mouseover and Field Mouseover .

This does not happen with Diuarnal Sect's Aspected Benefic.

**Comment by Alluneve** [comment]
This pertains shadowbringers era astrologian, is not reproduce able, can be closed
