### ISSUE TITLE
Moseover Action Plugin for Mouseover UI (play)astro not working as intended

### ISSUE THREAD

**Issue by AbombK** [Infiziert90/MOActionPlugin#44]
The action skill "play" would miss like half the time along with aspected benefic during nocturnal sect

**Comment by AbombK** [comment]
> I noticed this issue during raid yesterday, too. Several times, I'd have my mouse dead-center of a party member's frame in the party list, they'd be within 10y of me, and it would play the card on me anyway.
> 
> At first, I thought it was user error because the selection area of my group's caster, who I was playing the most cards on due to getting tons of ranged cards, was smaller vertically than the others, so I disabled the PartyListLayout plugin and restarted the game to ensure that I was using the default party list UI. That didn't fix it, so I thought it might have had to do with the "Stack entry fails if target is out of range" setting, so I disabled that.
> 
> However, it continued happening throughout the night, regardless of which party member I was targeting with the cards. Out of 196 cards played during that raid night, 28 were played on me despite my mouse location.

Yup, sounds about exactly what I experienced.  I thought it was buggy so I even disabled and re-enabled it as well.  I even took the mouseover UI and readded the stack.  Restarted the game.  Nothing seems to fix it.  We will just have to wait.

**Comment by daria-mianne** [comment]
This seems like it has probably been fixed now. In raid last night, I played 152 cards and all of them went to the correct target. If my previous 28 out of 196 was an accurate representation of the probability of the issue happening, then having 152 all go to the right target _without_ the bug being fixed would have a probability of around 1 in 15 billion. @AbombK are you still seeing this issue on the latest version?

**Comment by AbombK** [comment]
> This seems like it has probably been fixed now. In raid last night, I played 152 cards and all of them went to the correct target. If my previous 28 out of 196 was an accurate representation of the probability of the issue happening, then having 152 all go to the right target _without_ the bug being fixed would have a probability of around 1 in 15 billion. @AbombK are you still seeing this issue on the latest version?

It seems with the latest version that they may have corrected the "play" skill since it is working well now.  I know even now they have not corrected aspected benefic in nocturnal form because essential dignity works 100% of the time but aspected benefic doesn't.  I literally have it on the same person and if I use aspected benefic, it goes on me, but as soon as I use essential dignity no matter how much I spam it still works.  I appreciate that they fixed the bug for play but the issue for nocturnal aspected benefic still needs to be fixed.

**Comment by AbombK** [comment]
> @daria-mianne cards seems to be fixed, i have tested multiple times now with me just mashing play and minor arcana while casting malefic (with same gear the last time i tested it)
> 
> Nocturnal Sect Aspected Benefic still broken though

Yup, confirming the same test.

**Comment by Alluneve** [comment]
Another shadowbringers era astrologian issue, Ast being my main job in current expansion, everything with that works perfectly in current version.

Can be closed
