### ISSUE TITLE
UI mouseover action does not work on enemy list.

### ISSUE THREAD

**Issue by kygil85** [Infiziert90/MOActionPlugin#45]
I would assume that the UI mouseover would work on all UI, however it does not seem to work on the enemy list. Mostly not an issue but as a tank not being able to UI mouseover the enemy list to taunt is a bit of a letdown.

**Comment by DenL** [comment]
It works; I've been casting dots or taunting via enemy list. Should check you stack settings.

**Comment by kygil85** [comment]
Thanks for letting me know. Pretty sure I have a mouseover setup for taunt but ill double check.

**Comment by Alluneve** [comment]
Closable, non-issue
