### ISSUE TITLE
Stacks interact strangely with sub-GCD-cast time spells

### ISSUE THREAD

**Issue by evnhali** [Infiziert90/MOActionPlugin#46]
This is my stack for Stone/Cure (WHM):

![ffxiv_10212021_114741_334](https://user-images.githubusercontent.com/4701320/138338644-b570925d-85a1-4cc8-adb9-4515cbb358f2.png)

It works as expected under most circumstances. But if I press it with my mouse over a friendly target, while targeting an enemy target, when I'm on GCD but not currently casting a spell, during the ability queue window, it will queue Stone on the enemy target instead of Cure on the friendly mouseover.

The easiest way to reproduce this is to target an enemy, mouse over a friendly, and spam the button: it will alternate between casting Cure on the friendly and Stone on the enemy. Because of this, I initially thought the problem was that Cure went "on cooldown" until the end of its GCD (since the recast is longer than the cast time).

However, I can also reproduce it by casting Aero on an enemy target and then immediately trying to cast Cure on mouseover: it casts Stone on my target instead. So the GCD itself seems to be the issue.

Interestingly, an identical stack with the base ability set to Cure works perfectly as expected. So the problem isn't just "the base ability fires if the stack fails"; if that were the case then I'd be accidentally Curing myself when trying to spam it on mouseover, which isn't happening.

**Comment by Aelexe** [comment]
I seem to be having the same issue with a Riposte/Vercure (RDM) setup.

**Comment by Alluneve** [comment]
Closeable
