### ISSUE TITLE
feature request: fall through to next stack entry when target is invalid

### ISSUE THREAD

**Issue by adamkittelson** [Infiziert90/MOActionPlugin#49]
For example in this stack entry:
```
W3siQmFzZUlkIjozNTQyLCJTdGFjayI6W3siSXRlbTEiOiJVSSBNb3VzZW92ZXIiLCJJdGVtMiI6NzM4Mn0seyJJdGVtMSI6IlRhcmdldCBvZiBUYXJnZXQiLCJJdGVtMiI6NzM4Mn0seyJJdGVtMSI6IlNlbGYiLCJJdGVtMiI6MzU0Mn1dLCJNb2RpZmllciI6MCwiSm9iIjoiMTkifV0=
```

> Base Action -> Sheltron
> UI Mouseover -> Intevention
> Target of Target -> Intervention
> Self -> Sheltron

I would like to see a press of Sheltron cast intervention on the UI mouseover target if one is moused over, or the target of the current target (likely the MT), and then if that doesn't work then fall back to sheltron on the player.

I'm getting an "Invalid Target" error message when I have aggro of the target because it is trying to use Intervention on me. It falls through to the next stack entry if there is no target but does not fall through if the target is invalid. It'd be cool to also fall to the next stack entry when the target is invalid.

Thanks! Love the mod and the new more powerful customization system!

**Comment by Alluneve** [comment]
This falls under plugin guidelines of smart plugins that do thinking for you, at least that is my toughts behind it. 

"if I'm off tank I do not want to think and just press one button to automatically cast intervention on the main tank, but press sheltron if I'm the main tank" 

Closeable
