### ISSUE TITLE
Feature Request: Add actions to stacks not stacks to actions.

### ISSUE THREAD

**Issue by BoredDan** [Infiziert90/MOActionPlugin#50]
Having to setup the same stacks over and over for multiple spells/abilities is tedious and a pain. This also makes it harder to change the behaviour if you decide you would rather things work in a different manner. Right now we add stacks to actions, but a much less time consuming method would be to have us create the stacks and then assign which actions go onto those stacks. This is a bit of a bigger ask and would require a new UI, but ultimately it would create a much simpler and cleaner experience for the user and greatly reduce the time it takes to set things up.

**Comment by BoredDan** [comment]
Alternatively you could also get some of the same benefits by making the Base Action dropdown multiselect, or adding some sort of named/saved stack we can assign instead of each one being manually set up.

**Comment by attickdoor** [comment]
I see your point. It isn't the worst idea, but it would take significant reworking. Given that setup is a one-time cost, I'm not really inclined to care all that much.

**Comment by Alluneve** [comment]
This is still a valid issue!

Could rename and re-add that this pertains to a ui cleanup and the ability to re-order stacks.

Right now it loops through a list, and you cannot manually re-order the list as you please

**Comment by Infiziert90** [comment]
3212a88a8c0cfc1fe07d2db03ab47264784c456a added reordering of stacks, closing this a completed
