### ISSUE TITLE
feature request: fall through to next stack entry when "Action not yet learned."

### ISSUE THREAD

**Issue by anshu1101** [Infiziert90/MOActionPlugin#55]
For example, use Taurochole if not on cooldown otherwise Druochole. But if Taurochole is not yet learned Druochole is not used. Base action is Druochole in my case.

**Comment by nvillahermosa** [comment]
Commenting here instead of opening a new issue. I'm seeing this a lot with Reaper I have to disable the plugin when downscaled or else it fails on abilities that aren't learned and aborts the entire action stack.

**Comment by Alluneve** [comment]
Implementated
