### ISSUE TITLE
Doesn't work with Liturgy of the Bell

### ISSUE THREAD

**Issue by Fiorinol** [Infiziert90/MOActionPlugin#56]
The plugin simply doesn't work when using mouseover or self with Liturgy of the Bell, in spite of the fact that it works fine with Asylum.

Here is my setup:

https://i.imgur.com/w6Y112R.png

**Comment by FrUct1s** [comment]
Can confirm, WHM lvl 90 ability (Ground Target) Lithurgy of the Bell ONLY accepts "Mouse Location" in stacks

**Comment by Alluneve** [comment]
Closable, wasn't able to reproduce in current version
