### ISSUE TITLE
Action priority stacks (involving conditional spells/weaponskills) not functioning since update

### ISSUE THREAD

**Issue by Mike2k9** [Infiziert90/MOActionPlugin#57]
Action priority stacks have lost their functionality when conditional spells/weaponskills are involved (gemshine, verfire/verstone/blizzard IV, etc. etc.)

Normal macro's are just fine when using any sort of /action X /action Y macro using the game's built in system ex:
/macroicon "Gemshine"
/action "Gemshine"
/action "Ruin"

For more info: This functionality used to work before Endwalker, and Snowy's temporary version of MOAction for EW during December also supported this functionality. The logic (example) "if Gemshine not available, Ruin will be cast" has ceased to work.

Hopefully this issue will be resolved in a future update. Appreciate the time you took to bring this plugin back online prior to Savage raid week/during the holidays Attick.

**Comment by Mike2k9** [comment]
![macro](https://user-images.githubusercontent.com/95830632/147844874-081a45cc-a4e4-42a2-acf3-a498d24e5707.jpg)

Included an image for quick reference.

**Comment by NikkoToska** [comment]
I have the same issue, but a little different.  In scaled content, abilities that are no longer available due to the level cap will lockup the stack.  So if I have a level 90 ability at the top of the stack, nothing under it will run in level synced content.  I took a peek at the code, not enough to really get into it, but it seems that it checks 'not on cooldown' and 'has stacks', but that won't take into account that the level is insufficient, or in the case of Gemshine, that certain conditions need to be met to use.  The XIV Combo Plugin seems to be able to recognize when buttons are active or buffs exist, not sure what they're doing, but might be helpful.

**Comment by Mike2k9** [comment]
@NikkoToska 

You might want to try out https://github.com/UnknownX7/ReAction
ReAction is similar to MOAction and allows for some functionality that MOAction is currently unable to provide. It also has options to force a stack to fail, which could make stacks work when certain stacks have ability cooldowns in the mix.

Too much to explain here but you may want to give it a spin and experiment with it as an alternative to MOAction (I use both ingame as they cover each other pretty well)

**Comment by NikkoToska** [comment]
@Mike2k9 I'll give it a try.  Do you happen to know why the author of ReAction doesn't have it in Dalamud natively and does it through his own repository instead?  New to the whole plugin thing so just curious.

**Comment by Mike2k9** [comment]
It's not on Dalamud natively, since many of these plugins are variations of main plugins (ex there's XIVCombo and then there's XIVSlothCombo which is an alternative providing even more options), it would clutter the dalamud UI by listing all these alternatives, at least that's my understanding. UnknownX7 however is one of the main contributors to Dalamud plugins and colabs with many other plugin devs for Dalamud.

They usually have some repro steps on how to activate it on their pages. Often involves enabling experimental plugins and sometimes physically downloading the file or copying a link to activate the plugin. It's not too hard to set up. https://github.com/Nik-Potokar/XIVSlothCombo for example lists the repro steps at the top of the page, you can use that as reference.

**Comment by nvillahermosa** [comment]
> I have the same issue, but a little different. In scaled content, abilities that are no longer available due to the level cap will lockup the stack. So if I have a level 90 ability at the top of the stack, nothing under it will run in level synced content. 

I'm experiencing the same issue with downscaling leading to failed action stacks.

**Comment by Alluneve** [comment]
Closable, cannot change on game native behaviour of having a stack on a button you cannot press
