### ISSUE TITLE
Mouseovers Not Working on GNB Mitigation (Heart of Stone/Corundum, Aurora)

### ISSUE THREAD

**Issue by Axel-of-the-Key** [Infiziert90/MOActionPlugin#63]
Trying to set up basic mouseover actions as shown in the Youtube video and as I have seen others do. Just basic UI mouseover for these abilities (and other tank mitigations) does not seem to function. I have been able to get Target of Target working in some instances but other times it does not. Unsure what the issue here is. Action will just self-cast rather than casting on the targeting being moused over, whether on field or UI. I'm attaching a screenshot but I honestly don't think it really reveals anything you wouldn't otherwise assume.
![2022-01-26_14-03-56-616_Neneko_Daily Life  Gameplay _original](https://user-images.githubusercontent.com/8282745/151229526-e5d3474d-2cb3-453c-9b7c-74cc7aba7a2c.png)

**Comment by NikkoToska** [comment]
Tested it on my end, same results.

**Comment by Cuisette** [comment]
Same issue. Stack is set up the same way as I would use for every other healer and WAR Nascent.

**Comment by Axel-of-the-Key** [comment]
> Open your Actions/Traits menu, pull Heart of Corundum onto your bar. It should work now. It's still reading as Heart of Stone until you put the updated button on your bar fresh and new.

Ah, it seems like you always have to do this every time you change an ability with this plugin actually. Interesting. Good to know.

**Comment by Alluneve** [comment]
Closable, was fixed somewhere in endwalker
