### ISSUE TITLE
Unable to import presets

### ISSUE THREAD

**Issue by ohsynapse** [Infiziert90/MOActionPlugin#64]
Since the latest FFXIV patch (6.0.8) the ability to import preset strings for mouse over actions hasn't worked. The option to paste from clipboard flashes a windows quickly but doesn't paste the data. I have brought this up in the plugin issues discord but no response. Is this a known issue?

**Comment by Infiziert90** [comment]
Closing this, if the issue still exist in newer version please reopen this :)
