### ISSUE TITLE
[AST] Benefic mouseover not working

### ISSUE THREAD

**Issue by Gramgoyle** [Infiziert90/MOActionPlugin#65]
Benefic for some reason cant be cast using mouseover (I tested on both UI and Field mouseover).

If I set
[Base Action] as Benefic 
[Ability] Benefic [Target] UI Mouseover / Field Mouseover
 [Ability] Benefic II [Target] UI Mouseover / Field Mouseover
 --- BOTH Benefic and Benefic II can NOT be mouseover
 
 If I set
[Base Action] as Benefic II
[Ability] Benefic [Target] UI Mouseover / Field Mouseover
 [Ability] Benefic II [Target] UI Mouseover / Field Mouseover
 --- Benefic can NOT be mouseover
 --- Benefic II work fine

**Comment by jasperfirecai2** [comment]
you can't tell it to pick whichever spell is better, if you don't have benefic 2 learned benefic won't like you having benefic 2 in there
