### ISSUE TITLE
Does not seem to work for Sage

### ISSUE THREAD

**Issue by LylikaRayne** [Infiziert90/MOActionPlugin#66]
Out side of the equivalent of a swift cast Raise combo. None of the stacks I have set up for Sage works. I don't know if there is something going on. I have tried setting it for the name of the upgraded abilities and that doesn't even work. I use a combination of Target of target, and target stacks so that I can still attack and stay targeted onto the tank. 
![image](https://user-images.githubusercontent.com/100137815/158064001-d8dc7cf3-3424-4b49-8855-c3b8e3e4bb73.png)
All of those are set up the exact same as the one dropped down, please assist. I have tried deleting the stacks and remaking them. I've tried removing the plugin and reinstalling. As mentioned above I've even gone as far as in the past changing the names to the upgraded version of the ability.

**Comment by jasperfirecai2** [comment]
what exactly isn't working? how this should work is if you cat dosis on your tank it dosises the tank's target. what is actually happening?

**Comment by joker-119** [comment]
I'm having the same issues for all sage heals for mouseovers.
Esuna works, other classes work, but none of the sage abilities obey the action stack, they just cast on myself or my target as if moaction isn't installed.

**Comment by wetfly** [comment]
Same for me, none of my Sage stacks work. They work again if I remove them and set up them again, but once I relaunch the game they break again.

**Comment by icesharkk** [comment]
This is happening to me. So far I have been able to fix it by disabling and re-enabling MOAction from the dalmund menu. it appears to continue working even after zone transition but after login or some other trigger it will break again.

**Comment by Infiziert90** [comment]
Closing this, if the issue still exist in newer version please reopen this :)
