### ISSUE TITLE
Sge stacks causing frame drops in game

### ISSUE THREAD

**Issue by Ratnihsa** [Infiziert90/MOActionPlugin#72]
Noticed recently that I was getting frame spikes on riva tuner  in relation to using sage spells with MOaction.  It affects all spells even not tied to a stack, also using an in game macro will causing even further spikes.  Was able to reproduce on 2 systems and a friend as well as able to reproduce. First picture is using diag  , and second is using an in game macro not tied to any stack.
![1](https://user-images.githubusercontent.com/109928262/180671935-d316cce4-de39-4a2e-a159-19a9ba1c4f1a.png)
![2](https://user-images.githubusercontent.com/109928262/180671858-dc41e275-ad9d-48e2-ab45-253552da3fa7.png)

**Comment by Grandorg22** [comment]
did you tried without MOA enabled if they still drop maybe post it to the OF then.

**Comment by Ratnihsa** [comment]
The only time it gets frame drops using the plugin is on the sage class. Any other class using the plugin does not cause frame drops.

**Comment by Ratnihsa** [comment]
6.2 update frame drops still happening :<

**Comment by Infiziert90** [comment]
Closing this, if the issue still exist in newer version please reopen this :)
