### ISSUE TITLE
Swiftcast Stacks only work with WHM - "Cannot use as current Class." error on AST/SCH/SGE/SMN/BLM/RDM

### ISSUE THREAD

**Issue by FrUct1s** [Infiziert90/MOActionPlugin#73]
Swiftcast Stacks only work with WHM

![image](https://user-images.githubusercontent.com/58904408/186638802-7e439774-3834-440e-9352-4404e6b8c5a8.png)

**Comment by Aqua-1994** [comment]
added a reference, 

there's a bug in MoActionPlugin where your selected job on an action does not matter.
so when you have multiple jobs where you have a stack on swift cast, it takes the stack first in the internal index of stacks. (probably not this stack,...)

there's a fix for this in pull requests

**Comment by Alluneve** [comment]
fixed, closable
