### ISSUE TITLE
Will not install with launcher

### ISSUE THREAD

**Issue by Miaka808** [Infiziert90/MOActionPlugin#74]
After the recent patch, MOAction will not install, nor update for me.  It creates the folder file in the installed plugins listing, but gives the following error:
![Screenshot 2022-08-27 233958](https://user-images.githubusercontent.com/112300005/187057788-f521918c-6120-4465-97d2-50fb65eae3c1.jpg)

When I open the file installed plugins however, it does consistently create a file folder every time, deleting this folder and reinstalling it has not corrected the issue:

![Screenshot 2022-08-27 234150](https://user-images.githubusercontent.com/112300005/187057809-c62ee05d-9af3-43f1-9a95-d5c0e368c03c.jpg)

**Comment by Infiziert90** [comment]
Closing this, if the issue still exist in newer version please reopen this :)
