### ISSUE TITLE
WHM Regen not being added to stacks

### ISSUE THREAD

**Issue by unez96** [Infiziert90/MOActionPlugin#75]
Just like title says, Regen is just not being added even though I have gone through the process of adding it multiple times. Everything looks normal until I hit save and it's not added to the list of stacks.

**Comment by Alluneve** [comment]
presume this was a old save/delete issue with handling to saving stacks, need to doublecheck

**Comment by Infiziert90** [comment]
Closing this for now, if the issue still exists, please open a new issue :)
