### ISSUE TITLE
Ground Target problems

### ISSUE THREAD

**Issue by MMOProblems** [Infiziert90/MOActionPlugin#88]
Currently if I hover over the boss it automatically places things, like Asylum, directly centered on the boss even though I have not set these abilities in my stacks.  I want to double click these abilities to precisely drop them where I want them so having the plugin auto place them on target on a single click is an issue for me.  I dont recall this being a problem before the most recent update but I also have not played whm or any other ground targetting job in a little while.

**Comment by MMOProblems** [comment]
Just to quickly add to this, it seems to only happen if I try to use these abilities while casting another spell (so ability queuing is causing the issue I guess?).  And also I know its this plugin because disabling it completely removes the issue.

**Comment by RSPadilha** [comment]
Animation lock is queuing everything to target

**Comment by BitingHalberd** [comment]
Adding that I am experiencing this problem as well. It's a big problem for ninja especially due to it causing Shukuchi to fire instantly towards the target (usually the boss) if used right after any GCD.

**Comment by Infiziert90** [comment]
Closing this for now, if the issue still exists, please open a new issue :)
