### ISSUE TITLE
Menu modifier

### ISSUE THREAD

**Issue by darkt1981** [Infiziert90/MOActionPlugin#92]
Im sorry to ask this but why did you go with the "menu" as a modifier button instead of Alt?

you do know when you press Menu/Windows keys it will basicly put the game into background mode and it will stop reacting to your commands?

Seems a bit of a weird key pick. Could this be changed to Alt instead of windows key?

**Comment by Aqua-1994** [comment]
While it might be a misnomer, the MENU option is your ALT key as a modifier.
it comes like that out of Dalamud.

**Comment by Infiziert90** [comment]
5da93aef502a2751377db1f9ef49684741c72ebe
