### ISSUE TITLE
Mousover crosshair?

### ISSUE THREAD

**Issue by rurupupu** [Infiziert90/MOActionPlugin#93]
Is it possible to implement a kind of crosshair (adjustable of course) in the middle of the screen (adjustable of course) to act as a mousover target? (target any player model in this circle's radius)
Would be very useful for controller players for example to aim at a teammate directly as a monk and thunderclap to them directly. And i think there are way more possible use cases for that feature/

**Comment by darkt1981** [comment]
doesnt move over all ready target the thing your pointing at ?
And as for custom mouse, there are tools out there for this which work on all games.
i believe "Yolomouse" is one of those.

**Comment by rurupupu** [comment]
Not an option. 
crosshair disappears after using controller inputs. Yolomouse one too

**Comment by Alluneve** [comment]
This can be reclassified as a feature request for a static new TargetType called: "the middle of my _goddamn screen_" and a toggle to turn on/off a visual crosshair on the middle of your _goddamn screen_

**Comment by Alluneve** [comment]
Good news @rurupupu, I got an object reference from a specific x/y coordinate.
Bad news: I have no clue how I would draw a crosshair at that location, so it's currently an invisible location

https://github.com/Infiziert90/MOActionPlugin/pull/111

**Comment by Alluneve** [comment]
[Completed ](https://www.youtube.com/watch?v=b_jKBvD4a7s)
