### ISSUE TITLE
Healing NPCs

### ISSUE THREAD

**Issue by ItsKaterina** [Infiziert90/MOActionPlugin#98]
Hi there, I am looking to see if there is a solution to healing an NPC? This specifically comes up in DSR with healing Haurchefant. 

To give some context - Typically I have all my healing set to ui/field mouseover and I use party frames or player names to mouseover and heal people. With DSR and healing Haurchefaunt I cannot do this and my heals will instead heal me. 

Is there any known work around for this issue? 

Any help would be greatly appreciated :)

**Comment by Aqua-1994** [comment]
this concerns how the plugin (master branch) currently decides if a target is an enemy or friendly.

If https://github.com/attickdoor/MOActionPlugin/pull/97 ever gets pulled in, that would solve it.
it's the long standing role-quest bug.

**Comment by Alluneve** [comment]
This is fixed, can be closed.
