### ISSUE TITLE
Sage's Icarus failing

### ISSUE THREAD

**Issue by Exobrem** [Infiziert90/MOActionPlugin#99]
So I have this issue where if I mouseover a party member, either through the UI Mouseover or Field Mouseover and I attempt to use Icarus, it will always take me to the enemy instead of the party member if I retarget the enemy and use Dosis before my cast is complete. 

Basically, Icarus would only work if my cast was finished and my GCD was rolling before using Icarus on someone. I was able to replicate this on a couple target dummies. (It didn't need to be a party member.) 

My stack copied from clipboard

W3siQmFzZUlkIjoyNDI5NSwiU3RhY2siOlt7Ikl0ZW0xIjoiVGFyZ2V0IiwiSXRlbTIiOjI0Mjk1fSx7Ikl0ZW0xIjoiVUkgTW91c2VvdmVyIiwiSXRlbTIiOjI0Mjk1fSx7Ikl0ZW0xIjoiRmllbGQgTW91c2VvdmVyIiwiSXRlbTIiOjI0Mjk1fV0sIk1vZGlmaWVyIjowLCJKb2IiOiI0MCJ9XQ==

**Comment by Aqua-1994** [comment]
this probably has to do with ingame queueing, I'll try to replicate and see if I can fix this, once 7.0 is fully released.

**Comment by Kshumishyn** [comment]
I've been experiencing this a lot as well. It always seems to prioritize my target, it's quite frustrating. I haven't tried Monk but I wonder if this would occur on it as well.

**Comment by Alluneve** [comment]
@Exobrem and @Kshumishyn any of you willing to share a small clip of this behaviour in action?

**Comment by Kshumishyn** [comment]
My apologies, I was not able to recreate it, I'm missing some condition for this to happen, it seems like Exobrem understands how to recreate it a bit better than I do. If I happen to record it happening I will bring it here next time.

Maybe this is only occurs with abnormally large hitboxes and the fact that I can't prioritize Allies over Enemies plays into this.

**Comment by Kshumishyn** [comment]
> @Exobrem and @Kshumishyn any of you willing to share a small clip of this behaviour in action?

I have been able to catch it on camera. I am hesitant to post videos with names in it but I do have a picture of the very frame I pressed it right, before it took me to the boss (and subsequent AoE, ow) instead of the player I'm pointing to.
![image](https://github.com/user-attachments/assets/f11573b9-9581-46d1-813c-0a28dd0611b4)

If you'd like I can link the clip as well, though I'm not sure how to do so privately.

Here are my Icarus Mouseover settings, you can see me trying to force priority, but it will do the same whether I put Target there or not.

![image](https://github.com/user-attachments/assets/c4ef22c6-93ac-43cd-8548-8610e7c616fc)

**Comment by Alluneve** [comment]
> Would the "Stack entry fails if target is out of range" checkbox fix this situation? I've not a good gauge of distance, but maybe the Target is the only valid distance it can resolve. I just want my Target to basically never be an option for Icarus unless I MO it.

if that is on, it would indeed go to the next line in the action and icarus to your target.
if you get it reproducible, would you kindly try it out without the last line in your stack, without the bottom line to icarus to target?

**Comment by Kshumishyn** [comment]
I'll try to get another clip, I had it occur again, ironically with Aetherial Manipulation w/ Black Mage in Frontline where it behaves like Icarus. It satisfied the conditions you requested above, but I forgot to clip it. My only suspicion was that my MO teammate was not a valid target (I don't recall whether he was same Alliance).

**Comment by Alluneve** [comment]
> I'll try to get another clip, I had it occur again, ironically with Aetherial Manipulation w/ Black Mage in Frontline where it behaves like Icarus. It satisfied the conditions you requested above, and even went to an enemy completely 100% beyond a doubt, off-screen, but I forgot to clip it. My only suspicion was that my MO teammate was not a valid target (I don't recall whether he was same Alliance).

this specifically shouldn't work in PVP though. so that's an oddity there...

**Comment by Infiziert90** [comment]
Closing this for now, if the issue still exists, please open a new issue :)
